-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/opv_receiver_HDL_coder_input/OPVReceiv_ip_src_OPV_Receiver.vhd
-- Created: 2024-02-14 00:32:11
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 3.69004e-06
-- Target subsystem base rate: 3.69004e-06
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: OPVReceiv_ip_src_OPV_Receiver
-- Source Path: opv_receiver_HDL_coder_input/OPV Receiver
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY OPVReceiv_ip_src_OPV_Receiver IS
  PORT( received_i                        :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        received_q                        :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        audio_or_data                     :   OUT   std_logic_vector(15 DOWNTO 0)  -- int16
        );
END OPVReceiv_ip_src_OPV_Receiver;


ARCHITECTURE rtl OF OPVReceiv_ip_src_OPV_Receiver IS

BEGIN
  audio_or_data <= received_i;

END rtl;

